apiVersion: v1
kind: Config

clusters:
- cluster:
    server: http://authwebhook:8080/authorize
  name: remote-authz

users:
- name: apiserver

current-context: webhook
contexts:
- context:
    cluster: remote-authz
    user: apiserver
  name: webhook
